import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Email for verification: 22f2001173@ds.study.iitm.ac.in

# --------------------------------------------------
# Generate Sample Employee Dataset (100 Records)
# --------------------------------------------------
np.random.seed(42)

departments = ["HR", "Finance", "IT", "Marketing", "Operations"]
regions = ["North", "South", "East", "West"]

df = pd.DataFrame({
    "Employee_ID": range(1, 101),
    "Department": np.random.choice(departments, size=100),
    "Region": np.random.choice(regions, size=100),
    "Performance_Score": np.random.randint(1, 6, size=100)
})

df.to_csv("employee_data.csv", index=False)  # Save dataset


# --------------------------------------------------
# Frequency count for HR department
# --------------------------------------------------
hr_count = (df["Department"] == "HR").sum()
print(f"Number of employees in HR department = {hr_count}")


# --------------------------------------------------
# Histogram visualization
# --------------------------------------------------
plt.figure(figsize=(8, 5))
sns.countplot(x="Department", data=df)
plt.title("Employee Distribution by Department")
plt.xlabel("Department")
plt.ylabel("Count")
plt.grid(axis="y")

plt.tight_layout()
plt.savefig("department_histogram.png")
plt.close()


# --------------------------------------------------
# Convert output to HTML file
# --------------------------------------------------
html_content = f"""
<html>
<head><title>Employee Performance Report</title></head>
<body>

<h1>Employee Performance Report</h1>

<h2>HR Department Count</h2>
<p>Total number of employees in HR department: <b>{hr_count}</b></p>

<h2>Sample Dataset Preview</h2>
{df.head().to_html(index=False)}

<h2>Department Histogram</h2>
<img src="department_histogram.png" width="600">

<p>Generated by email: 22f2001173@ds.study.iitm.ac.in</p>

</body>
</html>
"""

with open("employee_report.html", "w") as file:
    file.write(html_content)

print("Report generated → employee_report.html")
